### ISSUE TITLE
Further work on R Development Guide

### ISSUE THREAD

**Issue by hturner** [rstats-gsod/gsod2022#3]
There are several issues on the [repo](https://github.com/r-devel/rdevguide/issues) for the [R Development Guide](https://contributor.r-project.org/rdevguide/) that could be addressed in a GSoD project.

I would highlight:
 * Add chapter on translations (https://github.com/r-devel/rdevguide/issues/34)
 * More information (a new chapter?) on tests for base R (https://github.com/r-devel/rdevguide/issues/28)
 * Describing a git workflow for testing proposed patches (https://github.com/r-devel/rdevguide/issues/23)
 * Novice-friendly instructions on installing R from source (https://github.com/r-devel/rdevguide/issues/33 - as a companion to the official documentation https://cran.r-project.org/doc/manuals/r-release/R-admin.html)
 
These extensions, plus addressing the smaller miscellaneous issues could easily form a GSoD project.

**Comment by SaranjeetKaur** [comment]
If we go ahead with this project, I would be interested to work on this in the capacity of Technical Writer. There are quite a few things to upgrade the R Dev Guide as it is now.

This would be a meaningful project for me as there is already a lot of feedback collected to incorporate into the first draft of the R Dev Guide. It would also be a natural transition to the GSoD program as we complete the participation in the Digital Infrastructure Incubator at Code for Science & Society and have feedback available from several participants and people who join us at the Campfires.

In the same vein, we can may be submit a proposal at https://www.writethedocs.org/conf/portland/2022/news/tickets-on-sale/ (deadline to submit proposals is Feb 25). I'll take a couple of days to spin up ideas around this conference proposal.

**Comment by imanishbarnwal** [comment]
Hey @hturner, is the organization still accepting proposals for GSOD. If yes, then I would like to go with work on this issue. I was a technical writer at @opendaylight I worked on their projects and wrote user guides.

**Comment by hturner** [comment]
Hi @imanishbarnwal, thanks for you interest but we have hired writers for this project - https://github.com/rstats-gsod/gsod2022/wiki/GSoD-2022-Writers

I will close the 2022 issues to clarify this.
