### ISSUE TITLE
CRAN-related project

### ISSUE THREAD

**Issue by hturner** [rstats-gsod/gsod2022#4]
One issue is to convert the CRAN website to a more modern and accessible format: https://github.com/RConsortium/r-repositories-wg/issues/5#issuecomment-1021697261.

This might not make a documentation project in itself. However, possibly documentation surrounding CRAN may be helpful, e.g.
 - Documenting specifications of the CRAN check systems
 - Documenting common reasons for rejecting packages submissions and how to fix them. A small example that I helped with recently:  message from CRAN
    > "Packages in Suggests should only be used conditionally on their availability, as they may not be installed and the package should not fail in that case (particularly not in examples nor tests)."
    
    The solution is documented in https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages, but a problem & solution style documentation would be more helpful to novice developers.

**Comment by benubah** [comment]
Happy to help here.

**Comment by aryanxk02** [comment]
Hi, @hturner I was going through the ideas list for Google Season of Docs 2022. I came across the accepted proposal titled, [Expand and Reorganize the R Development Guide.](https://developers.google.com/season-of-docs/docs/participants#:~:text=Expand%20and%20Reorganize%20the%20R%20Development%20Guide) After going through the [issues](https://github.com/rstats-gsod/gsod2022/issues) list present in this repository, the current issue (idea for GSoD 2022) i.e converting the CRAN website to a more modern framework has caught my attention.

I am looking forward to knowing more about the project considering my previous experience with CRAN packages during my Google Summer of Code 2021 with OSGeo. Here is my [link](https://github.com/aryanxk02/mapmint/wiki/GSoC-2021:-Final-Report) to the Final Report for GSoC 2021. 

I am quite interested in working on this project. I am thinking of using [Docusaurus](https://docusaurus.io/) to achieve the goal. Do check it out. Basically, it is a tool developed to generate/publish documentation websites. I have tried Docusaurus earlier and I think it goes well with the current problem statement.

Do let me know what you think about this. Hoping for a positive response.

Thank you :)

**Comment by hturner** [comment]
Closing this issue as we went with #3 for GSoD 2022 and we have hired writers for this project - https://github.com/rstats-gsod/gsod2022/wiki/GSoD-2022-Writers

If people would like to work on this issue on a voluntary basis or plan to make a proposal to another funding source, please reach out via one of the following:
 - [R-Devel Slack](https://contributor.r-project.org/slack) #core-documentation channel
 - [R Contribution Working Group meetings](https://contributor.r-project.org/events/)
 - [R Contributors Twitter](https://twitter.com/R_Contributors) DM

This idea can also be proposed for GSoD 2023 when that repo is set up.
