### ISSUE TITLE
Incorporating native pipe in documentation

### ISSUE THREAD

**Issue by elinw** [rstats-gsod/gsod2022#6]
Inspired by an exchange on Bugzilla, I think there is a good case to systematically incorporate the native pip (`|>`) examples across the help files. This would also provide a good opportunity to also improve examples and text in help files in general.  In addition to https://bugs.r-project.org/buglist.cgi?bug_status=__open__&component=Documentation&list_id=19298&product=R  which contains multiple issues about these files, many other issues are about undocumented behaviors

**Comment by hturner** [comment]
This could be a good topic for a dedicated sprint, or an activity in the upcoming Bug Barbecue at useR! (https://github.com/r-devel/rcontribution/issues/18).

Alternatively (as it seems likely we will focus on other ideas for GSoD), this might be a good project for Google Summer of Code - might you be interested in co-mentoring such a project?

**Comment by elinw** [comment]
A sprint is a good idea.  I don't think it is enough of a code project for GSoC, that's why they created a separate documentation thing.

**Comment by hturner** [comment]
Fair point. We'll keep in it mind for future activities then.

**Comment by hturner** [comment]
Closing this issue as we went with #3 for GSoD 2022 and we have hired writers for this project - https://github.com/rstats-gsod/gsod2022/wiki/GSoD-2022-Writers

If people would like to work on this issue on a voluntary basis or plan to make a proposal to another funding source, please reach out via one of the following:
 - [R-Devel Slack](https://contributor.r-project.org/slack) #core-documentation channel
 - [R Contribution Working Group meetings](https://contributor.r-project.org/events/)
 - [R Contributors Twitter](https://twitter.com/R_Contributors) DM

This idea can also be proposed for GSoD 2023 when that repo is set up.
