### ISSUE TITLE
Document useR! website template

### ISSUE THREAD

**Issue by benubah** [rstats-gsod/gsod2022#7]
May be a sub-idea for GSoD 2022 or completely for the future:

useR! website serves a global and diverse audience every year.

Document the useR! website template and  make it easy for organizers who don't have web development experience to easily setup and add content in an accessible way and also avoid inaccessible work-arounds like using an image to display sponsorship tables (e.g https://user2022.r-project.org/about/sponsorship/)

Automatic translation could be explored alongside

**Comment by C-mmon** [comment]
I can take up the issue.

**Comment by hturner** [comment]
Closing this issue as we went with #3 for GSoD 2022 and we have hired writers for this project - https://github.com/rstats-gsod/gsod2022/wiki/GSoD-2022-Writers

If people would like to work on this issue on a voluntary basis or plan to make a proposal to another funding source, please reach out via one of the following:
 - [R-Devel Slack](https://contributor.r-project.org/slack) #core-documentation channel
 - [R Contribution Working Group meetings](https://contributor.r-project.org/events/)
 - [R Contributors Twitter](https://twitter.com/R_Contributors) DM

This idea can also be proposed for GSoD 2023 when that repo is set up.
